Build - fix node version
https://nodejs.org/en/download/releases/

A JavaScript error occurred in the main process
Uncaught Exception:
Error: The module '/tmp/.org.chromium.Chromium.zvzfCO'
was compiled against a different Node.js version using
NODE_MODULE_VERSION 59. This version of Node.js requires
NODE_MODULE_VERSION 57. Please try re-compiling or re-installing
the module (for instance, using `npm rebuild` or `npm install`).
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:186:18)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/Costlocker/resources/app.asar/node_modules/desktop-idle/index.js:1:176)
    at Object.<anonymous> (/Costlocker/resources/app.asar/node_modules/desktop-idle/index.js:3:3)