Idle time - fix building native windows module
https://github.com/tessel/node-usb/issues/140
https://electronjs.org/docs/tutorial/using-native-node-modules#installing-modules-and-rebuilding-for-electron

App threw an error during load
Error: The system cannot find message text for message number 0x%1 in the message file for %2.
\\?\C:\Users\Zdenda\Desktop\electron\electron-v3\node_modules\desktop-idle\build\Release\desktopIdle.node
    at process.module.(anonymous function) [as dlopen] (ELECTRON_ASAR.js:172:20)
    at Object.Module._extensions..node (module.js:671:18)
    at Object.module.(anonymous function) [as .node] (ELECTRON_ASAR.js:172:20)
    at Module.load (module.js:561:32)
    at tryModuleLoad (module.js:504:12)
    at Function.Module._load (module.js:496:3)
    at Module.require (module.js:586:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (C:\Users\Zdenda\Desktop\electron\electron-v3\node_modules\desktop-idle\index.js:1:176)
    at Object.<anonymous> (C:\Users\Zdenda\Desktop\electron\electron-v3\node_modules\desktop-idle\index.js:3:3)